spring.application.name=english
spring.datasource.url=jdbc:postgresql://postgres:5432/word
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8086
server.servlet.context-path=/english